// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvz6Jonz1ONYNX8Dc_daLRl0PWKysSIzQ',
    appId: '1:341950453724:web:5c85aa31f5a2f4d891a119',
    messagingSenderId: '341950453724',
    projectId: 'hanger-e3499',
    authDomain: 'hanger-e3499.firebaseapp.com',
    storageBucket: 'hanger-e3499.firebasestorage.app',
    measurementId: 'G-5XJF5VZM9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXFBpuEZ11ww4mQHmWfZ9WygDTbdtvUgs',
    appId: '1:341950453724:android:a65856c0b197874d91a119',
    messagingSenderId: '341950453724',
    projectId: 'hanger-e3499',
    storageBucket: 'hanger-e3499.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1R-1t2bC1VYRXg6nr_-gaoznIlUAmKJc',
    appId: '1:341950453724:ios:78123995f540beb791a119',
    messagingSenderId: '341950453724',
    projectId: 'hanger-e3499',
    storageBucket: 'hanger-e3499.firebasestorage.app',
    iosBundleId: 'com.example.hanger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1R-1t2bC1VYRXg6nr_-gaoznIlUAmKJc',
    appId: '1:341950453724:ios:78123995f540beb791a119',
    messagingSenderId: '341950453724',
    projectId: 'hanger-e3499',
    storageBucket: 'hanger-e3499.firebasestorage.app',
    iosBundleId: 'com.example.hanger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvz6Jonz1ONYNX8Dc_daLRl0PWKysSIzQ',
    appId: '1:341950453724:web:1a96efe3d143d74591a119',
    messagingSenderId: '341950453724',
    projectId: 'hanger-e3499',
    authDomain: 'hanger-e3499.firebaseapp.com',
    storageBucket: 'hanger-e3499.firebasestorage.app',
    measurementId: 'G-R2GBXST7KG',
  );
}
